services:
  postgres:
    image: postgres:16-alpine
    container_name: karen-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: karen
      POSTGRES_PASSWORD: karen_password
      POSTGRES_DB: karen_khodro

    ports:
      - "5432:5432"

    volumes:
      - karen_db:/var/lib/postgresql/data

volumes:
  karen_db: